substitutions:
  name: smart-fairy-light-dimmer

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini
  name_add_mac_suffix: true
  project:
    name: jeffresc.smart-fairy-light-dimmer
    version: "1.0"

logger:

api:

ota:

dashboard_import:
  package_import_url: github://JeffResc/Smart-Fairy-Light-Dimmer/esphome-d1-mini.yaml

wifi:
  ap:
    password: "jeffresc"

captive_portal:

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  id: bus_a

switch:
  - platform: restart
    name: ${name} Restart
    id: restart_switch

sensor:
  - platform: shtcx
    temperature:
      name: ${name} Temperature
      filters:
      - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: ${name} Humidity
    update_interval: 60s

light:
  - platform: monochromatic
    name: ${name} LD1
    output: LD1_output
    id: LD1
    gamma_correct: false
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: monochromatic
    name: ${name} LD2
    output: LD2_output
    id: LD2
    gamma_correct: false
    restore_mode: RESTORE_DEFAULT_OFF

output:
  - platform: esp8266_pwm
    id: LD1_output
    pin: GPIO16
    # You may want to configure a maximum power output depending on your particular lights, to ensure they are not damaged by being over-powered.
    max_power: 0.60
    frequency: 1220Hz
  - platform: esp8266_pwm
    id: LD2_output
    pin: GPIO13
    # You may want to configure a maximum power output depending on your particular lights, to ensure they are not damaged by being over-powered.
    max_power: 0.60
    frequency: 1220Hz
